package mainmenujava;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;

/**
 *
 * @author Vo Tue Nam CE140557
 */
public class HelpNew extends javax.swing.JFrame {

    /**
     * Creates new form HelpNew
     */
    public HelpNew() {
        CustomCursor();
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/2.png")));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    public void CustomCursor(){
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("mousecontrol.png");
        Point point = new Point(0, 0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        setCursor(cursor);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoExit = new javax.swing.JLabel();
        wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Help Form");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoExitMouseClicked(evt);
            }
        });
        getContentPane().add(LogoExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 70, 70));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Newhelp!.png"))); // NOI18N
        getContentPane().add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoExitMouseClicked
        MainMenu m = new MainMenu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoExitMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoExit;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
