package mainmenujava;

import jaco.mp3.player.MP3Player;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Vo Tue Nam CE140557
 */
public class MainMenu extends javax.swing.JFrame {

    public static String string;
    //public static final String SONG = "0.mp3";
   // MP3Player mP3Player = new MP3Player(new File(SONG));
    ranking rank =null;
    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        CustomCursor();
        //mP3Player.play();
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/2.png")));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //mP3Player.play();

    }

    public void CustomCursor() {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("mousecontrol.png");
        Point point = new Point(0, 0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        setCursor(cursor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EffectButton = new javax.swing.JLabel();
        lblLeaderboard = new javax.swing.JLabel();
        PlayNow = new javax.swing.JLabel();
        AboutUs = new javax.swing.JLabel();
        Help = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Bacgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EffectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/4.gif"))); // NOI18N
        getContentPane().add(EffectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        lblLeaderboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLeaderboardMouseClicked(evt);
            }
        });
        getContentPane().add(lblLeaderboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 230, 80));

        PlayNow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayNowMouseClicked(evt);
            }
        });
        getContentPane().add(PlayNow, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 300, 100));

        AboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsMouseClicked(evt);
            }
        });
        getContentPane().add(AboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 290, 100));

        Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HelpMouseClicked(evt);
            }
        });
        getContentPane().add(Help, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 280, 90));

        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 520, 200, 100));

        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Login.png"))); // NOI18N
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 110, 210, 70));

        Bacgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NewMenu.png"))); // NOI18N
        getContentPane().add(Bacgound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayNowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayNowMouseClicked
        colorblock cl = new colorblock();
        this.setVisible(false);
        cl.setVisible(true);
    }//GEN-LAST:event_PlayNowMouseClicked

    private void AboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsMouseClicked
        AboutUsNew ab = new AboutUsNew();
        ab.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AboutUsMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    private void HelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HelpMouseClicked
        HelpNew hp = new HelpNew();
        hp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HelpMouseClicked

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        LoginNew abc = new LoginNew();
        abc.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_LoginMouseClicked

    private void lblLeaderboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLeaderboardMouseClicked
        try {
            DBManagement db = new DBManagement();
            Connection conn = db.getConnected();
            ScoresManagement a = new ScoresManagement(conn);
           // string = a.saveBXH();
            //BXH abc = new BXH();
            a.load();
           rank = new ranking(a.getSocre());
            //rank.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblLeaderboardMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutUs;
    private javax.swing.JLabel Bacgound;
    private javax.swing.JLabel EffectButton;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Help;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel PlayNow;
    private javax.swing.JLabel lblLeaderboard;
    // End of variables declaration//GEN-END:variables
}
