package mainmenujava;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Vo Tue Nam CE140557
 */
public class RegisterNew extends javax.swing.JFrame {

    /**
     * Creates new form RegisterNew
     */
    public RegisterNew() {
        CustomCursor();
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/2.png")));
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public void CustomCursor(){
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image img = toolkit.getImage("mousecontrol.png");
        Point point = new Point(0, 0);
        Cursor cursor = toolkit.createCustomCursor(img, point, "Cursor");
        setCursor(cursor);    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtFullname = new javax.swing.JTextField();
        passConfirmPassword = new javax.swing.JPasswordField();
        passPassWord = new javax.swing.JPasswordField();
        lblOkey = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblException = new javax.swing.JLabel();
        Backgound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register Form");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 220, 30));

        txtFullname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFullname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtFullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 222, 220, 30));

        passConfirmPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passConfirmPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(passConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 220, -1));

        passPassWord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passPassWord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(passPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 220, -1));

        lblOkey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOkeyMouseClicked(evt);
            }
        });
        getContentPane().add(lblOkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 140, 50));

        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        getContentPane().add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 110, 50));

        lblException.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblException.setForeground(new java.awt.Color(255, 0, 0));
        lblException.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblException, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 260, 20));

        Backgound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/regiter.png"))); // NOI18N
        getContentPane().add(Backgound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOkeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOkeyMouseClicked
        lblException.setText("");
        UserManagemnet obj = new UserManagemnet();
        obj.Update();
        boolean check = false;
        String username = txtUsername.getText();
        String password = passPassWord.getText();
        String cfPassword = passConfirmPassword.getText();
        if(username==""){
            lblException.setText("Username cannot be empty!");
            check = false;
        }
        if (password.equals(cfPassword) == false) {
            lblException.setText("Error: Pass and ConfirmPass must be the same!");
            check = false;
        } else if (obj.isDuplicateUser(username)){
            lblException.setText("Error: User duplicate");
            check = false;
        } else if (password.length()<8||password.length()>20){
            lblException.setText("Error: Password must 8-20 char");
            check=false;
        }
        else {
            lblException.setText("");
            check = true;
        }
        while (check == true) {
            try {
                DBManagement db = new DBManagement();
                Connection con = db.getConnected();
                PreparedStatement posted = con.prepareStatement("INSERT INTO `account`(`ac_username`, `ac_password`) VALUES ('" + username + "',MD5('" + password + "'))");
                posted.executeUpdate();
            } catch (SQLException ex) {
                System.out.println(ex);
            } finally {
                System.out.println("Insert done!");
                check=false;
                this.dispose();
                LoginNew login = new LoginNew();
                login.setVisible(true);
            }
        }
    }//GEN-LAST:event_lblOkeyMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        LoginNew login = new LoginNew();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgound;
    private javax.swing.JLabel lblException;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblOkey;
    private javax.swing.JPasswordField passConfirmPassword;
    private javax.swing.JPasswordField passPassWord;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
